### ISSUE TITLE
Please add a README

### ISSUE THREAD

**Issue by probonopd** [abrandemuehl/trilateration#1]
Code looks interesting. Please add a README that describes what it is, how to compile, and how to use.

**Comment by abrandemuehl** [comment]
Sure. I'll add that now

**Comment by abrandemuehl** [comment]
I've added a README with what seemed relevant to me. It may be a bit rambling because I wrote it quickly, but I think the content is there.

If you have any other questions, feel free to reopen this issue/open a new issue to ask them.

**Comment by probonopd** [comment]
Thanks for writing the README and for the clarification of the code and status of the project. Very inspiring!
